### PR TITLE
Create zhCN.lua

### PR DESCRIPTION
**Pull request by T3rdW**
Create zhCN.lua

### CODE REVIEW

**Comment by RagedUnicorn** [comment]
Hi @T3rdW 

Thank you very much for your contribution. I have some small changes that you would need to make before I can merge this pullrequest.
I saw that you also made a second pullrequest. Those pullrequest however should be merged together as one. A pullrequest should contain a working unit and both of the pullrequests can't work without the other.

Can I ask you to apply the change from https://github.com/RagedUnicorn/wow-classic-gearmenu/pull/51 to the pullrequest https://github.com/RagedUnicorn/wow-classic-gearmenu/pull/52

Also additionally it is important to understand that the file that you changed in pullrequest 51 is a generated file. The file is generated by the maven build process.

To update the toc file of the addon you would actually need to update the following two files:

https://github.com/RagedUnicorn/wow-classic-gearmenu/blob/master/build-resources/gearmenu-release.toc.tpl
https://github.com/RagedUnicorn/wow-classic-gearmenu/blob/master/build-resources/gearmenu-development.toc.tpl

Then afterwards execute the mvn command to build the project

`mvn generate-resources -Dgenerate.sources.overwrite=true -P development`

This generates the proper toc file. I'm not sure if you are familiar with maven and how it works. If you don't want to make the changes yourself you could also follow this guide and I can add the changes myself to the pullrequest
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

This change in the setting would allow me to modify your pullrequest and the merge it.

Again thanks for your contribution and sorry that it took me a while to respond here.

Cheers,
RagedUnicorn

**Comment by T3rdW** [comment]
I can't see the request
"In the right sidebar of your pull request, select Allow edits from maintainers. You can change these permissions at any time by unadvocacy this option."
I have applied for a pull request again, and this option is available nowhttps://github.com/RagedUnicorn/wow-classic-gearmenu/pull/55#issue-380777423. Please check if it can be modified. I am not familiar with the operation of github, I am sorry

**Comment by RagedUnicorn** [comment]
Hm I can't seem to be able to modify. If you want I can copy and paste your changes into the project. The only bad thin with this is that the work is then not attributed to your name. If you are okay with that hovever I will gladly copy it into the project.

Btw I just saw that there also some translations missing. The following keys are missing from your file.

```lua
rggm.L["enable_fastpress"] = "Enable Fastpress"
rggm.L["enable_fastpress_tooltip"] = "Enables actions to be triggered on a keypress down instead on keypress up"

rggm.L["size_slider_title"] = "Gearslot size"
rggm.L["size_slider_tooltip"] = "Modify the size of the Gearslots. Different elements will also adapt to the "
  .. "size of the Gearslot"

rggm.L["unable_to_find_equipslot"] = "Unable to find a matching slot for itemId %s"
rggm.L["unable_to_find_item"] = "Unable to find any itemInfo for itemId %s"
```

**Comment by T3rdW** [comment]
I have updated the missing translation content, you can check #55. If it still cannot be modified, you can gladly copy it into the project. I'm really sorry.

**Comment by RagedUnicorn** [comment]
Hi Thank you again for helping with this. While I was unable to modify the pullrequest I took your changes and modified them until it worked. You can see the commit here:

https://github.com/RagedUnicorn/wow-classic-gearmenu/commit/72cd3e157ddb85eada52e9d7f1fc64e7c453e8ca

You are added as a co-author of the commit!

I also need to add some more text because I worked on some features in the meantime. I was only able to translate them with google translate and I'm sure the text aren't that good :)

Would be happy to update the text from the ones below I you want to translate them.

```
  rggm.L["enable_fastpress"] = "Enable Fastpress" TODO
  rggm.L["enable_fastpress_tooltip"] = "Enables actions to be triggered on a keypress down instead on keypress up" TODO

  rggm.L["size_slider_title"] = "Gearslot size" TODO
  rggm.L["size_slider_tooltip"] = "Modify the size of the Gearslots. Different elements will also adapt to the "
    .. "size of the Gearslot" TODO

  rggm.L["unable_to_find_equipslot"] = "Unable to find a matching slot for itemId %s"
  rggm.L["unable_to_find_item"] = "Unable to find any itemInfo for itemId %s"
```

I will try to do a release as soon as possible. I need to do one anyway because Blizzard updated wow to 1.13.4

Cheers
RagedUnicorn

**Comment by T3rdW** [comment]
rggm.L["enable_fastpress"] = "启动快速按键"
  rggm.L["enable_fastpress_tooltip"] = "允许在按键下压时触发操作而不是在按键抬起时触发操作"
  
  rggm.L["size_slider_title"] = "齿轮槽大小"
  rggm.L["size_slider_tooltip"] = "修改齿轮槽的大小.不同的元素也会适应"
    .. "齿轮槽的大小"
	
  rggm.L["unable_to_find_equipslot"] = "无法为物品Id找到匹配的槽位 %s"
  rggm.L["unable_to_find_item"] = "无法为物品Id找到指定的物品信息 %s"

**Comment by RagedUnicorn** [comment]
Hi @T3rdW 

Updated this. Thank you so much!

Release v1.3.0 just went out and it contains all this changes. I'm closing this pull request.

Regards,
RagedUnicorn

**Pull request closed without merging**
