### PR TITLE
Update locales.

### PR DESCRIPTION
**Pull request by EKE00372**
Add zhTW/zhCN locales.
Add missing translate in code/GM_ItemManager.lua
Use Global strings instead custom locale text on Item quality.

Feature request: Add a option for disable debug mode to avoid lots message in chat.

### CODE REVIEW

**Comment by RagedUnicorn** [comment]
Hi @EKE00372,

Thanks for the pull request. I'm not quite sure about some changes you did. There is no need to translate messages that are in any of mod.logger.LogXXX. Those are development messages and should always be in english. They are for the developer and not the player that uses the addon. That player should never see those messages.

Also while some of the stuff inside the locale files seem repetitive and might be improved with a for loop I really want to avoid to much logic in the locale files.

Cheers,
RagedUnicorn

**Comment by EKE00372** [comment]
>That player should never see those messages.
but mod.logger.Log show for ppl in game
>They are for the developer and not the player that uses the addon.
I only do changes on msg which notice unable add/remove rule, that was i think not only for developer.

You can take translate or ask me to revert changes, or just don't want locales for zhTW/zhCN

**Comment by EKE00372** [comment]
Please told me if you want zh translate or not

**Comment by RagedUnicorn** [comment]
Hi @EKE00372,

To be honest as of right now I would rather not include them. I'm a bit unsure about adding locales that I don't speak at all because I can only really check what it means with google translate and if I add more features I'm not able to provide the translation anyway. Really appreciate the effort though!

Cheers,
RagedUnicorn

**Comment by EKE00372** [comment]
not sure is it my language skill issue, although you don speak it still can be added, i mean if need a new pr for zhTW/CN locale only or not because this pr is already closed......

**Pull request closed without merging**
